### ISSUE TITLE
Search TSR not returning negative answers for answeringorganisationid 

### ISSUE THREAD

**Issue by jdewilde** [Informatievlaanderen/GIPOD#162]
The operation /api/v1/trench-synergy-requests does not return any TSR's if I set the answeringorganisationid and the answer value to false.
The TSR 10213693 should be returned.

**Comment by AIV-Bert** [comment]
Hi @jdewilde,

This should be fixed. Could you check this and provide feedback?

Kind regards,

Bert

**Comment by jdewilde** [comment]
HI @AIV-Bert,
I still don't receive the TSR's where my answer was false.
Jeroen

https://api-gateway.beta.gipod.vlaanderen.be/api/v1/trench-synergy-requests?answeringorganisationid=0C1BBF13-A7F6-0FAE-B555-759A61E5C675&answer=false

**Comment by AIV-Bert** [comment]
Hi @jdewilde,

Is this issue still relevant? Can you reproduce this with a different TSR?

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
Closed due to inactivity
